# This is a basic workflow to help you get started with Actions
# workflow - цепочка действий
# Имя процесса Билдится на всех типах 📦 🐍
name: CMake Build Matrix

on: 
  push:
    paths-ignore: 
      - 'LICENSE'
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore: 
      - 'LICENSE'
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }} 
    strategy:
      matrix:
        os:
        - ubuntu-latest
        build_type:
        - "Release"
        generators:
        - "Ninja"

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build
          ninja --version
          cmake --version
          gcc --version

      - name: cache vcpkg
        uses: actions/cache@v3
        with:
          path: /usr/local/share/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-download-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-download-${{ matrix.os }}-
            ${{ runner.os }}-vcpkg-download-
      - uses: actions/cache@v3
        with:
          path: /usr/local/share/vcpkg/installed
          key: ${{ runner.os }}-vcpkg-installed-${{ matrix.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-installed-${{ matrix.os }}-
            ${{ runner.os }}-vcpkg-installed-
      - name: Install libraries with vcpkg
        run: |
          vcpkg install curl[ssl,http2,tool] protobuf benchmark gtest glog breakpad
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
            -G "${{ matrix.generators }}" \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: cmake --build ./build --config ${{ matrix.build_type }}
      - name: Test
        shell: bash
        run: cd build && ctest
        