# This is a basic workflow to help you get started with Actions
# workflow - цепочка действий
# Имя процесса Билдится на всех типах 📦 🐍
name: CMake Build Matrix

on: 
  push:
    paths-ignore: 
      - 'LICENSE'
      - '.gitignore'
      - 'README.md'
  pull_request:
    paths-ignore: 
      - 'LICENSE'
      - '.gitignore'
      - 'README.md'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.config.os }} 
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            os: ubuntu-latest,
            artifact: "ubuntu_gcc.7z",
            build_type: "Release",
            cc: "gcc",
            cxx: "g++",
            archiver: "7z a",
            generators: "Ninja"
          }

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install ninja-build
          ninja --version
          cmake --version
          gcc --version

      - name: cache vcpkg
        uses: actions/cache@v3
        with:
          path: /usr/local/share/vcpkg/downloads
          key: ${{ runner.os }}-vcpkg-download-${{ matrix.config.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-download-${{ matrix.config.os }}-
            ${{ runner.os }}-vcpkg-download-
      - uses: actions/cache@v3
        with:
          path: /usr/local/share/vcpkg/installed
          key: ${{ runner.os }}-vcpkg-installed-${{ matrix.config.os }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-installed-${{ matrix.config.os }}-
            ${{ runner.os }}-vcpkg-installed-
      - name: Install libraries with vcpkg
        run: |
          vcpkg install curl[ssl,http2,tool] protobuf benchmark
          
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Configure
        shell: bash
        run: |
          mkdir build
          mkdir instdir
          cmake \
            -S . \
            -B . \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -G "${{ matrix.config.generators }}" \
            -DCMAKE_INSTALL_PREFIX:PATH=instdir
      - name: Build
        shell: bash
        run: cmake --build . --config ${{ matrix.config.build_type }}
        